### ISSUE TITLE
See through merging and branching changesets

### ISSUE THREAD

**Issue by fmallet** [lg2de/sonar-scm-tfvc#24] opened 2016-04-28 07:56 UTC
Only EDIT changes are checked at the moment.
But perhaps MERGE and BRANCH changes should also be checked.

Steps to reproduce:
- Create a file, make a few edits and check-ins
- Now branch it: {{tf branch file.txt branched_file.txt}}
- Check the change in
- The annotation will fail on {{branched_file.txt}}, with the error message {{Unable to TFS annotate the following file which is not yet checked-in}}

The expected behavior at that point should be to have the same output as for {{file.txt}} itself.

Then, let's look at the merge:
- Update {{branches_file.txt}} by adding a line to it, and check that it (changeset #X)
- Merge it back: {{tf merge branched_file.txt file.txt}}, check that in (changeset #X+1)

The expected output is to see changeset #X, and not #X+1, on the newly added line of test.txt.

Relates to #5

**Comment by sopelt** [comment] 2017-01-03 13:04
Hello, any chance that there is progress on this front in the foreseeable future? I noticed that there is a PR at https://github.com/SonarQubeCommunity/sonar-scm-tfvc/pull/32 concerned with this that is yet to be reviewed/commented/integrated.
Kind regards

**Comment by BlackAngelTiger** [comment] 2017-10-04 05:01
Hello, I would also like to see this enhancement been implemented. This is one of the blocker for use to use the TFVC integration in SonarQube.

**Comment by jabbera** [comment] 2017-10-04 12:00
No one is supporting this plugin anymore. I’m sure sonar is taking volunteers.

**Comment by lg2de** [comment] 2020-01-17 09:38
Recently I created a new SQ project for a branch in TFS.
I found that the annotation in SQ is correct with the current plugin version.
Maybe it is fixed in between either by the plugin code (before I tool repository responsibility) or by the TFS API.

Therefore I'm going to close this issue.

If you think the problem is still existing, do not hesitate to contact me.

**Closed by lg2de** 2020-01-17 09:38 UTC
Labels: enhancement
