### ISSUE TITLE
"Unable to TFS annotate the following file which is not in a mapped TFS workspace"

### ISSUE THREAD

**Issue by HamsterExAstris** [lg2de/sonar-scm-tfvc#40] opened 2017-08-01 05:28 UTC
While SonarQube can correctly do annotation when I run the compile locally, it's not working for TFS from us. It keeps erroring with "Unable to TFS annotate the following file which is not in a mapped TFS workspace" on all of the files.

I know there have been some attempts in the past to solve this issue (https://github.com/SonarQubeCommunity/sonar-scm-tfvc/pull/7, https://github.com/SonarQubeCommunity/sonar-scm-tfvc/pull/13); we have v2.6.2 of the TFVC plugin installed which has those fixes. Apparently clearing the cache isn't doing it for us.

When I try checking Workstation.Current.IsMapped(path) myself post-build, it's returning true. So I have no idea why it's not doing so when SonarTfsAnnotate.exe is run during the build.

We're running TFS2012, and still using old-school TFSBuild.proj-based builds, with our .targets file is invoking SonarQube.Scanner.MSBuild.exe begin/end at the appropriate times. (The TFS2013 object model is installed.)

I'm out of ideas as to what the issue could be. Any thoughts on what I could look at, or other information I could provide?

**Comment by jabbera** [comment] 2017-08-02 15:32
This plugin has no maintainer:-(

**Comment by wilsade** [comment] 2018-12-28 09:20
HI.
Does it works with Visual Studio 2017?
I am using Sonar 6.7.5.38563.
Thanks.

**Comment by lg2de** [comment] 2019-07-16 18:26
This issue is quite old and I'm unable to reproduce it.
Therefore I'm going to close it for now.
Feel free to reopen with further details.

**Closed by lg2de** 2019-07-16 18:26 UTC
