### ISSUE TITLE
Unable to automatic assign issues 

### ISSUE THREAD

**Issue by marc-pinyol** [lg2de/sonar-scm-tfvc#37] opened 2017-05-04 07:19 UTC
Hi,

We're facing problems with functionality of automatically assign issues. Checking logs we see this error that we believe that is related:

##[error]ERROR: Unable to TFS annotate the project which raised the following authentication exception: TF30063: You are not authorized to access https://XXXXXXX.visualstudio.com/DefaultCollection/.
##[error]WARN: Missing blame information for the following files: ...

We're using sonarqube 6.1 and TFVC 2.1.2

Best regards,
Marc

**Comment by lg2de** [comment] 2019-07-16 18:20
This is an authentication issue.
I'm unable to reproduce it, therefore I close it for now.
Feel free to reopen with further details.

**Closed by lg2de** 2019-07-16 18:20 UTC
